buildscript {
    ext {
        daggerHilt = '2.57.2'
    }

    repositories {
        google()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath "com.google.dagger:hilt-android-gradle-plugin:$daggerHilt"
    }

}
plugins {
    id 'com.google.dagger.hilt.android' version "$daggerHilt" apply false
    id 'com.diffplug.spotless' version '6.25.0' apply false
}

tasks.register('clean', Delete) {
    delete layout.buildDirectory
}


