buildscript {
    repositories {
        google()
        mavenCentral()

    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
        classpath 'com.google.dagger:hilt-android-gradle-plugin:2.57.1'
    }

}
plugins {

    id 'com.google.dagger.hilt.android' version '2.57.1' apply false
}
allprojects {


}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}

ext {

    rxjava2Version = '2.1.6'
    rxandroidVersion = '2.0.1'
}