plugins {
    id 'com.android.application'
    id 'com.google.dagger.hilt.android'

}

apply plugin: 'com.android.application'
apply plugin: 'com.google.dagger.hilt.android'

def appVersionCode = 41
def appVersionName = "2.3.${appVersionCode}"

def gitCommitHashProvider = providers.exec {
    commandLine 'git', 'rev-parse', '--short', 'HEAD'
}.standardOutput.asText.map { it.trim() }

ext.gitCommitHash = gitCommitHashProvider

tasks.register("copyChangelog", Copy) {
    description = "Copies CHANGELOG.md from root to res/raw"
    group = "build"

    from("${rootDir}/CHANGELOG.md")
    into("${projectDir}/src/main/res/raw")
    rename { "changelog.md" }
}

preBuild.dependsOn("copyChangelog")

// -------------------------------
// LOAD secret.properties
// -------------------------------
def secretPropsFile = rootProject.file("app/secret.properties")
def secretProps = new Properties()

if (secretPropsFile.exists()) {
    secretProps.load(new FileInputStream(secretPropsFile))
} else {
    throw new GradleException("🔥 secret.properties is missing! Create app/secret.properties")
}



android {
    compileSdkVersion 36
    buildFeatures {
        viewBinding = true
        dataBinding = true
        buildConfig = true
    }

    bundle {
        language {
            enableSplit = true
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }
    packagingOptions {
        resources {
            excludes += ['META-INF/DEPENDENCIES', 'META-INF/LICENSE', 'META-INF/LICENSE.txt', 'META-INF/license.txt', 'META-INF/NOTICE', 'META-INF/NOTICE.txt', 'META-INF/notice.txt', 'META-INF/ASL2.0']
        }
    }
    defaultConfig {
        applicationId "com.pasich.mynotes"
        minSdkVersion 26
        targetSdkVersion 36

        versionCode appVersionCode
        versionName appVersionName

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation": "$projectDir/schemas".toString()]
            }
        }
        resValue "string", "whatNewVersion", "\"🔥 v${versionName}\""
        buildConfigField "String", "GIT_COMMIT_HASH", "\"${gitCommitHashProvider.get()}\""
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "String", "ATTACH_KEY", "\"${secretProps['ATTACH_KEY']}\""
        }
        debug {
            debuggable true
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            buildConfigField "String", "ATTACH_KEY", "\"${secretProps['ATTACH_KEY']}\""
        }

    }
    hilt {
        enableAggregatingTask = true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace = 'com.pasich.mynotes'
    lint {
        abortOnError false
    }
}


ext {
    markwon_version = '4.6.2'
    powerPrefenceVersion = '2.1.0'
    roomVersion = '2.8.1'
}
dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.preference:preference:1.2.1'
    implementation "androidx.lifecycle:lifecycle-viewmodel:2.9.4"
    implementation 'androidx.core:core-splashscreen:1.0.1'
    implementation 'androidx.activity:activity:1.11.0'

    //DI (Hilt)
    implementation "com.google.dagger:hilt-android:$daggerHilt"
    annotationProcessor "com.google.dagger:hilt-compiler:$daggerHilt"

    //Reactive
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'

    //Room
    implementation "androidx.room:room-rxjava2:$roomVersion"
    annotationProcessor "androidx.room:room-compiler:$roomVersion"

    //Pay Billing
    implementation 'com.google.android.play:app-update:2.1.0'
    implementation 'com.android.billingclient:billing:8.0.0'

    //Other lib (Gson/Glide/PowerPreferences)
    implementation 'com.google.code.gson:gson:2.13.2'
    implementation "com.github.AliAsadi:PowerPreference:$powerPrefenceVersion"

    //Markwon https://noties.io/Markwon/docs/v4/
    implementation"io.noties.markwon:core:$markwon_version"
    implementation"io.noties.markwon:ext-strikethrough:$markwon_version"
    implementation"io.noties.markwon:linkify:$markwon_version"
    

}
